version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: mycrud_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: mycrud
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d mycrud"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pg_data:
